/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package testing.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.16.0)", date = "2022-06-29")
public class AddressBookThrift implements org.apache.thrift.TBase<AddressBookThrift, AddressBookThrift._Fields>, java.io.Serializable, Cloneable, Comparable<AddressBookThrift> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("AddressBookThrift");

  private static final org.apache.thrift.protocol.TField PEOPLE_FIELD_DESC = new org.apache.thrift.protocol.TField("people", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new AddressBookThriftStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new AddressBookThriftTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.util.List<PersonThrift> people; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PEOPLE((short)1, "people");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PEOPLE
          return PEOPLE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PEOPLE, new org.apache.thrift.meta_data.FieldMetaData("people", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, PersonThrift.class))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(AddressBookThrift.class, metaDataMap);
  }

  public AddressBookThrift() {
  }

  public AddressBookThrift(
    java.util.List<PersonThrift> people)
  {
    this();
    this.people = people;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public AddressBookThrift(AddressBookThrift other) {
    if (other.isSetPeople()) {
      java.util.List<PersonThrift> __this__people = new java.util.ArrayList<PersonThrift>(other.people.size());
      for (PersonThrift other_element : other.people) {
        __this__people.add(new PersonThrift(other_element));
      }
      this.people = __this__people;
    }
  }

  public AddressBookThrift deepCopy() {
    return new AddressBookThrift(this);
  }

  @Override
  public void clear() {
    this.people = null;
  }

  public int getPeopleSize() {
    return (this.people == null) ? 0 : this.people.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<PersonThrift> getPeopleIterator() {
    return (this.people == null) ? null : this.people.iterator();
  }

  public void addToPeople(PersonThrift elem) {
    if (this.people == null) {
      this.people = new java.util.ArrayList<PersonThrift>();
    }
    this.people.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<PersonThrift> getPeople() {
    return this.people;
  }

  public AddressBookThrift setPeople(@org.apache.thrift.annotation.Nullable java.util.List<PersonThrift> people) {
    this.people = people;
    return this;
  }

  public void unsetPeople() {
    this.people = null;
  }

  /** Returns true if field people is set (has been assigned a value) and false otherwise */
  public boolean isSetPeople() {
    return this.people != null;
  }

  public void setPeopleIsSet(boolean value) {
    if (!value) {
      this.people = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case PEOPLE:
      if (value == null) {
        unsetPeople();
      } else {
        setPeople((java.util.List<PersonThrift>)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case PEOPLE:
      return getPeople();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case PEOPLE:
      return isSetPeople();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof AddressBookThrift)
      return this.equals((AddressBookThrift)that);
    return false;
  }

  public boolean equals(AddressBookThrift that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_people = true && this.isSetPeople();
    boolean that_present_people = true && that.isSetPeople();
    if (this_present_people || that_present_people) {
      if (!(this_present_people && that_present_people))
        return false;
      if (!this.people.equals(that.people))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetPeople()) ? 131071 : 524287);
    if (isSetPeople())
      hashCode = hashCode * 8191 + people.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(AddressBookThrift other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetPeople(), other.isSetPeople());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPeople()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.people, other.people);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("AddressBookThrift(");
    boolean first = true;

    sb.append("people:");
    if (this.people == null) {
      sb.append("null");
    } else {
      sb.append(this.people);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class AddressBookThriftStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public AddressBookThriftStandardScheme getScheme() {
      return new AddressBookThriftStandardScheme();
    }
  }

  private static class AddressBookThriftStandardScheme extends org.apache.thrift.scheme.StandardScheme<AddressBookThrift> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, AddressBookThrift struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PEOPLE
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
                struct.people = new java.util.ArrayList<PersonThrift>(_list8.size);
                @org.apache.thrift.annotation.Nullable PersonThrift _elem9;
                for (int _i10 = 0; _i10 < _list8.size; ++_i10)
                {
                  _elem9 = new PersonThrift();
                  _elem9.read(iprot);
                  struct.people.add(_elem9);
                }
                iprot.readListEnd();
              }
              struct.setPeopleIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, AddressBookThrift struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.people != null) {
        oprot.writeFieldBegin(PEOPLE_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.people.size()));
          for (PersonThrift _iter11 : struct.people)
          {
            _iter11.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class AddressBookThriftTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public AddressBookThriftTupleScheme getScheme() {
      return new AddressBookThriftTupleScheme();
    }
  }

  private static class AddressBookThriftTupleScheme extends org.apache.thrift.scheme.TupleScheme<AddressBookThrift> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, AddressBookThrift struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetPeople()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetPeople()) {
        {
          oprot.writeI32(struct.people.size());
          for (PersonThrift _iter12 : struct.people)
          {
            _iter12.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, AddressBookThrift struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list13 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
          struct.people = new java.util.ArrayList<PersonThrift>(_list13.size);
          @org.apache.thrift.annotation.Nullable PersonThrift _elem14;
          for (int _i15 = 0; _i15 < _list13.size; ++_i15)
          {
            _elem14 = new PersonThrift();
            _elem14.read(iprot);
            struct.people.add(_elem14);
          }
        }
        struct.setPeopleIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

