// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package testing.protos;

public final class AddressBookProtos {
  private AddressBookProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_PersonProtos_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_PersonProtos_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_PersonProtos_PhoneNumberProtos_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_PersonProtos_PhoneNumberProtos_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_AddressBook_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_AddressBook_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021addressbook.proto\022\010tutorial\"\206\002\n\014Person" +
      "Protos\022\014\n\004name\030\001 \001(\t\022\n\n\002id\030\002 \001(\005\022\r\n\005emai" +
      "l\030\003 \001(\t\0228\n\006phones\030\004 \003(\0132(.tutorial.Perso" +
      "nProtos.PhoneNumberProtos\032_\n\021PhoneNumber" +
      "Protos\022\016\n\006number\030\001 \001(\t\022:\n\004type\030\002 \001(\0162&.t" +
      "utorial.PersonProtos.PhoneTypeProtos:\004HO" +
      "ME\"2\n\017PhoneTypeProtos\022\013\n\007MOBIILE\020\000\022\010\n\004HO" +
      "ME\020\001\022\010\n\004WORK\020\002\"5\n\013AddressBook\022&\n\006people\030" +
      "\001 \003(\0132\026.tutorial.PersonProtosB2\n\033com.exa" +
      "mple.tutorial.protosB\021AddressBookProtosP" +
      "\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_PersonProtos_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_PersonProtos_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_PersonProtos_descriptor,
        new java.lang.String[] { "Name", "Id", "Email", "Phones", });
    internal_static_tutorial_PersonProtos_PhoneNumberProtos_descriptor =
      internal_static_tutorial_PersonProtos_descriptor.getNestedTypes().get(0);
    internal_static_tutorial_PersonProtos_PhoneNumberProtos_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_PersonProtos_PhoneNumberProtos_descriptor,
        new java.lang.String[] { "Number", "Type", });
    internal_static_tutorial_AddressBook_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_AddressBook_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_AddressBook_descriptor,
        new java.lang.String[] { "People", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
