/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package testing.avro;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@org.apache.avro.specific.AvroGenerated
public class AddressBookAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 776229766056765051L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AddressBookAvro\",\"namespace\":\"com.example.tutorial.avro\",\"fields\":[{\"name\":\"people\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"PersonAvro\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"email\",\"type\":\"string\"},{\"name\":\"phones\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"PhoneNumberAvro\",\"fields\":[{\"name\":\"number\",\"type\":\"string\"},{\"name\":\"type\",\"type\":{\"type\":\"enum\",\"name\":\"PhoneTypeAvro\",\"symbols\":[\"MOBILE\",\"HOME\",\"WORK\"]}}]}}}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AddressBookAvro> ENCODER =
      new BinaryMessageEncoder<AddressBookAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AddressBookAvro> DECODER =
      new BinaryMessageDecoder<AddressBookAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AddressBookAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AddressBookAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AddressBookAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AddressBookAvro>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AddressBookAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AddressBookAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AddressBookAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AddressBookAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.List<PersonAvro> people;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AddressBookAvro() {}

  /**
   * All-args constructor.
   * @param people The new value for people
   */
  public AddressBookAvro(java.util.List<PersonAvro> people) {
    this.people = people;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return people;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: people = (java.util.List<PersonAvro>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'people' field.
   * @return The value of the 'people' field.
   */
  public java.util.List<PersonAvro> getPeople() {
    return people;
  }


  /**
   * Sets the value of the 'people' field.
   * @param value the value to set.
   */
  public void setPeople(java.util.List<PersonAvro> value) {
    this.people = value;
  }

  /**
   * Creates a new AddressBookAvro RecordBuilder.
   * @return A new AddressBookAvro RecordBuilder
   */
  public static AddressBookAvro.Builder newBuilder() {
    return new AddressBookAvro.Builder();
  }

  /**
   * Creates a new AddressBookAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AddressBookAvro RecordBuilder
   */
  public static AddressBookAvro.Builder newBuilder(AddressBookAvro.Builder other) {
    if (other == null) {
      return new AddressBookAvro.Builder();
    } else {
      return new AddressBookAvro.Builder(other);
    }
  }

  /**
   * Creates a new AddressBookAvro RecordBuilder by copying an existing AddressBookAvro instance.
   * @param other The existing instance to copy.
   * @return A new AddressBookAvro RecordBuilder
   */
  public static AddressBookAvro.Builder newBuilder(AddressBookAvro other) {
    if (other == null) {
      return new AddressBookAvro.Builder();
    } else {
      return new AddressBookAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for AddressBookAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AddressBookAvro>
    implements org.apache.avro.data.RecordBuilder<AddressBookAvro> {

    private java.util.List<PersonAvro> people;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(AddressBookAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.people)) {
        this.people = data().deepCopy(fields()[0].schema(), other.people);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing AddressBookAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(AddressBookAvro other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.people)) {
        this.people = data().deepCopy(fields()[0].schema(), other.people);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'people' field.
      * @return The value.
      */
    public java.util.List<PersonAvro> getPeople() {
      return people;
    }


    /**
      * Sets the value of the 'people' field.
      * @param value The value of 'people'.
      * @return This builder.
      */
    public AddressBookAvro.Builder setPeople(java.util.List<PersonAvro> value) {
      validate(fields()[0], value);
      this.people = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'people' field has been set.
      * @return True if the 'people' field has been set, false otherwise.
      */
    public boolean hasPeople() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'people' field.
      * @return This builder.
      */
    public AddressBookAvro.Builder clearPeople() {
      people = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AddressBookAvro build() {
      try {
        AddressBookAvro record = new AddressBookAvro();
        record.people = fieldSetFlags()[0] ? this.people : (java.util.List<PersonAvro>) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AddressBookAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<AddressBookAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AddressBookAvro>
    READER$ = (org.apache.avro.io.DatumReader<AddressBookAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    long size0 = this.people.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (PersonAvro e0: this.people) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      long size0 = in.readArrayStart();
      java.util.List<PersonAvro> a0 = this.people;
      if (a0 == null) {
        a0 = new SpecificData.Array<PersonAvro>((int)size0, SCHEMA$.getField("people").schema());
        this.people = a0;
      } else a0.clear();
      SpecificData.Array<PersonAvro> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<PersonAvro>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          PersonAvro e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new PersonAvro();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          long size0 = in.readArrayStart();
          java.util.List<PersonAvro> a0 = this.people;
          if (a0 == null) {
            a0 = new SpecificData.Array<PersonAvro>((int)size0, SCHEMA$.getField("people").schema());
            this.people = a0;
          } else a0.clear();
          SpecificData.Array<PersonAvro> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<PersonAvro>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              PersonAvro e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new PersonAvro();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










