/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package testing.avro;
@org.apache.avro.specific.AvroGenerated
public enum PhoneTypeAvro implements org.apache.avro.generic.GenericEnumSymbol<PhoneTypeAvro> {
  MOBILE, HOME, WORK  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PhoneTypeAvro\",\"namespace\":\"com.example.tutorial.avro\",\"symbols\":[\"MOBILE\",\"HOME\",\"WORK\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
