// automatically generated by the FlatBuffers compiler, do not modify

package testing.flatbuffers;

public final class PhoneTypeFlat {
  private PhoneTypeFlat() { }
  public static final byte Mobile = 0;
  public static final byte Home = 1;
  public static final byte Work = 2;

  public static final String[] names = { "Mobile", "Home", "Work", };

  public static String name(int e) { return names[e]; }
}

